version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://blockchain:etech1234@51.77.159.227:27017/collect?authSource=admin
    ports:
      - "5024:5000"